name: Docker Build
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mvn install
      run: ./mvnw install -DskipTests=true
    - name: mvn package
      run: ./mvnw package
    - name: docker build
      run: docker build -t streamflow ./
