branches:
  only:
    - main
dist: bionic
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      jdk: openjdk8
install:
  - ./mvnw install -DskipTests=true
script:
  - ./mvnw test
